/**
 * Lista completa de instrumentos disponibles en el Mercado Global Colombiano (MGC)
 * y mercados internacionales para inversión
 */

export type InstrumentType = 'etf' | 'stock' | 'bond_etf';
export type InstrumentMarket = 'colombia' | 'usa' | 'europe' | 'global';
export type InstrumentCategory =
  | 'sp500'           // S&P 500
  | 'total_market'    // Mercado total
  | 'international'   // Internacional
  | 'emerging'        // Mercados emergentes
  | 'bonds'           // Bonos
  | 'dividend'        // Dividendos
  | 'tech'            // Tecnología
  | 'colombia'        // Colombia ETFs
  | 'colombia_stock'  // Acciones colombianas (BVC)
  | 'mgc'             // Mercado Global Colombiano (acciones internacionales en BVC)
  | 'individual';     // Acciones individuales (USA directo)

export interface Instrument {
  id: string;
  ticker: string;
  tickerAlphaVantage?: string; // Ticker para Alpha Vantage si es diferente
  name: string;
  description: string;
  type: InstrumentType;
  category: InstrumentCategory;
  market: InstrumentMarket;
  currency: 'USD' | 'COP' | 'EUR';
  exchange: string;
  currentPriceCop: number;      // Precio aproximado en COP
  currentPriceOriginal: number; // Precio en moneda original
  icon: string;
  color: string;
  isAvailableInMGC: boolean;    // Disponible en Mercado Global Colombiano
  isPopular: boolean;           // Mostrar en lista de populares
}

// ============ ETFs POPULARES ============

export const ETF_INSTRUMENTS: Instrument[] = [
  // --- S&P 500 ---
  {
    id: 'ivv',
    ticker: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    description: 'Replica el índice S&P 500 de las 500 empresas más grandes de EE.UU.',
    type: 'etf',
    category: 'sp500',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 2268000,
    currentPriceOriginal: 540,
    icon: '🇺🇸',
    color: '#3C3B6E',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'voo',
    ticker: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    description: 'ETF de Vanguard que replica el S&P 500 con bajo costo',
    type: 'etf',
    category: 'sp500',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 2184000,
    currentPriceOriginal: 520,
    icon: '🇺🇸',
    color: '#8B0000',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'spy',
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    description: 'El ETF más grande y líquido que replica el S&P 500',
    type: 'etf',
    category: 'sp500',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 2520000,
    currentPriceOriginal: 600,
    icon: '🇺🇸',
    color: '#228B22',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'cspx',
    ticker: 'CSPX',
    tickerAlphaVantage: 'CSPX.L',
    name: 'iShares Core S&P 500 UCITS ETF',
    description: 'Versión UCITS del S&P 500, acumulativo (reinvierte dividendos)',
    type: 'etf',
    category: 'sp500',
    market: 'europe',
    currency: 'USD',
    exchange: 'LSE',
    currentPriceCop: 3108000,
    currentPriceOriginal: 740,
    icon: '🌍',
    color: '#1E40AF',
    isAvailableInMGC: true,
    isPopular: true,
  },

  // --- Mercado Total USA ---
  {
    id: 'vti',
    ticker: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    description: 'Todo el mercado de acciones de EE.UU. (más de 4000 empresas)',
    type: 'etf',
    category: 'total_market',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 1176000,
    currentPriceOriginal: 280,
    icon: '📈',
    color: '#8B0000',
    isAvailableInMGC: false,
    isPopular: true,
  },

  // --- Internacional ---
  {
    id: 'vxus',
    ticker: 'VXUS',
    name: 'Vanguard Total International Stock ETF',
    description: 'Acciones internacionales (ex-US) de mercados desarrollados y emergentes',
    type: 'etf',
    category: 'international',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 260400,
    currentPriceOriginal: 62,
    icon: '🌍',
    color: '#228B22',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'iwda',
    ticker: 'IWDA',
    tickerAlphaVantage: 'IWDA.L',
    name: 'iShares Core MSCI World UCITS ETF',
    description: 'Mercados desarrollados globales (23 países)',
    type: 'etf',
    category: 'international',
    market: 'europe',
    currency: 'USD',
    exchange: 'LSE',
    currentPriceCop: 558600,
    currentPriceOriginal: 133,
    icon: '🌐',
    color: '#0EA5E9',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'vt',
    ticker: 'VT',
    name: 'Vanguard Total World Stock ETF',
    description: 'Todo el mercado mundial de acciones en un solo ETF',
    type: 'etf',
    category: 'international',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 504000,
    currentPriceOriginal: 120,
    icon: '🌎',
    color: '#7C3AED',
    isAvailableInMGC: false,
    isPopular: true,
  },

  // --- Mercados Emergentes ---
  {
    id: 'vwo',
    ticker: 'VWO',
    name: 'Vanguard FTSE Emerging Markets ETF',
    description: 'Mercados emergentes (China, India, Brasil, etc.)',
    type: 'etf',
    category: 'emerging',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 189000,
    currentPriceOriginal: 45,
    icon: '🌏',
    color: '#DC2626',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'iemg',
    ticker: 'IEMG',
    name: 'iShares Core MSCI Emerging Markets ETF',
    description: 'Mercados emergentes con más de 2600 empresas',
    type: 'etf',
    category: 'emerging',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 218400,
    currentPriceOriginal: 52,
    icon: '🌏',
    color: '#EA580C',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'eimi',
    ticker: 'EIMI',
    tickerAlphaVantage: 'EIMI.L',
    name: 'iShares Core MSCI EM IMI UCITS ETF',
    description: 'Mercados emergentes UCITS, acumulativo',
    type: 'etf',
    category: 'emerging',
    market: 'europe',
    currency: 'USD',
    exchange: 'LSE',
    currentPriceCop: 126000,
    currentPriceOriginal: 30,
    icon: '🌏',
    color: '#F97316',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Bonos ---
  {
    id: 'bnd',
    ticker: 'BND',
    name: 'Vanguard Total Bond Market ETF',
    description: 'Bonos diversificados de grado de inversión',
    type: 'bond_etf',
    category: 'bonds',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 302400,
    currentPriceOriginal: 72,
    icon: '🛡️',
    color: '#4169E1',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'bndx',
    ticker: 'BNDX',
    name: 'Vanguard Total International Bond ETF',
    description: 'Bonos internacionales de grado de inversión',
    type: 'bond_etf',
    category: 'bonds',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 210000,
    currentPriceOriginal: 50,
    icon: '🌐',
    color: '#6366F1',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Dividendos ---
  {
    id: 'vym',
    ticker: 'VYM',
    name: 'Vanguard High Dividend Yield ETF',
    description: 'Empresas con altos dividendos',
    type: 'etf',
    category: 'dividend',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 525000,
    currentPriceOriginal: 125,
    icon: '💰',
    color: '#DAA520',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'schd',
    ticker: 'SCHD',
    name: 'Schwab U.S. Dividend Equity ETF',
    description: 'Empresas estadounidenses con historial de dividendos',
    type: 'etf',
    category: 'dividend',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 336000,
    currentPriceOriginal: 80,
    icon: '💵',
    color: '#16A34A',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Tecnología ---
  {
    id: 'qqq',
    ticker: 'QQQ',
    name: 'Invesco QQQ Trust',
    description: 'Las 100 empresas más grandes del NASDAQ (tecnología)',
    type: 'etf',
    category: 'tech',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 2100000,
    currentPriceOriginal: 500,
    icon: '💻',
    color: '#0891B2',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'vgt',
    ticker: 'VGT',
    name: 'Vanguard Information Technology ETF',
    description: 'Sector tecnológico de EE.UU.',
    type: 'etf',
    category: 'tech',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 2520000,
    currentPriceOriginal: 600,
    icon: '🖥️',
    color: '#7C3AED',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Colombia Local ---
  {
    id: 'icolcap',
    ticker: 'ICOLCAP',
    name: 'iShares COLCAP',
    description: 'Replica el índice COLCAP de la Bolsa de Colombia',
    type: 'etf',
    category: 'colombia',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 12500,
    currentPriceOriginal: 12500,
    icon: '🇨🇴',
    color: '#FCD116',
    isAvailableInMGC: false, // Es local, no MGC
    isPopular: true,
  },
  {
    id: 'hcolsel',
    ticker: 'HCOLSEL',
    name: 'Global X Colombia Select ETF',
    description: 'Acciones colombianas de mayor capitalización',
    type: 'etf',
    category: 'colombia',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 8500,
    currentPriceOriginal: 8500,
    icon: '🇨🇴',
    color: '#003893',
    isAvailableInMGC: false,
    isPopular: false,
  },
];

// ============ ACCIONES BOLSA DE VALORES DE COLOMBIA (BVC) ============

export const COLOMBIA_STOCK_INSTRUMENTS: Instrument[] = [
  // --- Sector Financiero ---
  {
    id: 'bcolombia',
    ticker: 'BCOLOMBIA',
    name: 'Bancolombia S.A.',
    description: 'Banco comercial más grande de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 35000,
    currentPriceOriginal: 35000,
    icon: '🏦',
    color: '#003366',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'pfbcolom',
    ticker: 'PFBCOLOM',
    name: 'Bancolombia S.A. (Preferencial)',
    description: 'Acción preferencial de Bancolombia con dividendo prioritario',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 32000,
    currentPriceOriginal: 32000,
    icon: '🏦',
    color: '#003366',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'bogota',
    ticker: 'BOGOTA',
    name: 'Banco de Bogotá S.A.',
    description: 'Uno de los bancos más antiguos y grandes de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 72000,
    currentPriceOriginal: 72000,
    icon: '🏦',
    color: '#0033A0',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'grupoaval',
    ticker: 'GRUPOAVAL',
    name: 'Grupo Aval Acciones y Valores',
    description: 'Holding financiero más grande de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 1100,
    currentPriceOriginal: 1100,
    icon: '🏛️',
    color: '#004990',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'pfaval',
    ticker: 'PFAVAL',
    name: 'Grupo Aval (Preferencial)',
    description: 'Acción preferencial del Grupo Aval',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 1050,
    currentPriceOriginal: 1050,
    icon: '🏛️',
    color: '#004990',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'occidente',
    ticker: 'OCCIDENTE',
    name: 'Banco de Occidente S.A.',
    description: 'Banco comercial colombiano del Grupo Aval',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 38000,
    currentPriceOriginal: 38000,
    icon: '🏦',
    color: '#00529B',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'davivienda',
    ticker: 'PFDAVVNDA',
    name: 'Banco Davivienda S.A. (Preferencial)',
    description: 'Tercer banco más grande de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 28000,
    currentPriceOriginal: 28000,
    icon: '🏦',
    color: '#ED1C24',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'corficolcf',
    ticker: 'CORFICOLCF',
    name: 'Corficolombiana S.A.',
    description: 'Corporación financiera más grande de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 24000,
    currentPriceOriginal: 24000,
    icon: '🏛️',
    color: '#1B365D',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'gruposura',
    ticker: 'GRUPOSURA',
    name: 'Grupo de Inversiones Suramericana',
    description: 'Holding de servicios financieros y seguros',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 25000,
    currentPriceOriginal: 25000,
    icon: '🛡️',
    color: '#00205B',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'pfgrupsura',
    ticker: 'PFGRUPSURA',
    name: 'Grupo Sura (Preferencial)',
    description: 'Acción preferencial del Grupo Sura',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 23000,
    currentPriceOriginal: 23000,
    icon: '🛡️',
    color: '#00205B',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'bvc',
    ticker: 'BVC',
    name: 'Bolsa de Valores de Colombia',
    description: 'Operadora del mercado de valores colombiano',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 9500,
    currentPriceOriginal: 9500,
    icon: '📊',
    color: '#0066B3',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Energía y Petróleo ---
  {
    id: 'ecopetrol',
    ticker: 'ECOPETROL',
    name: 'Ecopetrol S.A.',
    description: 'Empresa petrolera más grande de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 2200,
    currentPriceOriginal: 2200,
    icon: '🛢️',
    color: '#FFCC00',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'isa',
    ticker: 'ISA',
    name: 'Interconexión Eléctrica S.A.',
    description: 'Transmisión de energía eléctrica en Latinoamérica',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 18500,
    currentPriceOriginal: 18500,
    icon: '⚡',
    color: '#00A651',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'celsia',
    ticker: 'CELSIA',
    name: 'Celsia S.A.',
    description: 'Generación y distribución de energía eléctrica',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 4200,
    currentPriceOriginal: 4200,
    icon: '💡',
    color: '#F7931E',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'grupoenergiabog',
    ticker: 'GEB',
    name: 'Grupo Energía Bogotá S.A.',
    description: 'Transporte de gas natural y transmisión eléctrica',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 2450,
    currentPriceOriginal: 2450,
    icon: '🔥',
    color: '#0072BC',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'promigas',
    ticker: 'PROMIGAS',
    name: 'Promigas S.A.',
    description: 'Transporte y distribución de gas natural',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 9800,
    currentPriceOriginal: 9800,
    icon: '🔥',
    color: '#E31937',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'canacol',
    ticker: 'CNEC',
    name: 'Canacol Energy Ltd.',
    description: 'Exploración y producción de gas natural',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 8500,
    currentPriceOriginal: 8500,
    icon: '⛽',
    color: '#1E3A5F',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Industrial y Materiales ---
  {
    id: 'cemargos',
    ticker: 'CEMARGOS',
    name: 'Cementos Argos S.A.',
    description: 'Producción de cemento y concreto',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 7200,
    currentPriceOriginal: 7200,
    icon: '🏗️',
    color: '#00529B',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'pfcemargos',
    ticker: 'PFCEMARGOS',
    name: 'Cementos Argos (Preferencial)',
    description: 'Acción preferencial de Cementos Argos',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 6800,
    currentPriceOriginal: 6800,
    icon: '🏗️',
    color: '#00529B',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'grupoargos',
    ticker: 'GRUPOARGOS',
    name: 'Grupo Argos S.A.',
    description: 'Holding de infraestructura: cemento, energía, concesiones',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 16000,
    currentPriceOriginal: 16000,
    icon: '🏢',
    color: '#003E7E',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'pfgrupoargos',
    ticker: 'PFGRUPOARGOS',
    name: 'Grupo Argos (Preferencial)',
    description: 'Acción preferencial del Grupo Argos',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 14500,
    currentPriceOriginal: 14500,
    icon: '🏢',
    color: '#003E7E',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'mineros',
    ticker: 'MINEROS',
    name: 'Mineros S.A.',
    description: 'Extracción y procesamiento de oro',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 3800,
    currentPriceOriginal: 3800,
    icon: '⛏️',
    color: '#DAA520',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Consumo y Retail ---
  {
    id: 'nutresa',
    ticker: 'NUTRESA',
    name: 'Grupo Nutresa S.A.',
    description: 'Alimentos procesados: Noel, Zenú, Chocolates, Tosh',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 58000,
    currentPriceOriginal: 58000,
    icon: '🍫',
    color: '#E21A23',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'exito',
    ticker: 'EXITO',
    name: 'Almacenes Éxito S.A.',
    description: 'Cadena de retail: Éxito, Carulla, Surtimax',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 2800,
    currentPriceOriginal: 2800,
    icon: '🛒',
    color: '#FFCC00',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'fabricato',
    ticker: 'FABRICATO',
    name: 'Fabricato S.A.',
    description: 'Textiles y confecciones',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 8.5,
    currentPriceOriginal: 8.5,
    icon: '👔',
    color: '#1E3A5F',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'enka',
    ticker: 'ENKA',
    name: 'Enka de Colombia S.A.',
    description: 'Fibras sintéticas y resinas de PET',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 12,
    currentPriceOriginal: 12,
    icon: '🧵',
    color: '#00529B',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Telecomunicaciones y Tecnología ---
  {
    id: 'etb',
    ticker: 'ETB',
    name: 'Empresa de Telecomunicaciones de Bogotá',
    description: 'Telecomunicaciones: internet, telefonía, datos',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 280,
    currentPriceOriginal: 280,
    icon: '📡',
    color: '#0066B3',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'tigo',
    ticker: 'TIGO',
    name: 'Millicom (Tigo)',
    description: 'Telecomunicaciones móviles y servicios digitales',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 42000,
    currentPriceOriginal: 42000,
    icon: '📱',
    color: '#00377B',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Transporte e Infraestructura ---
  {
    id: 'clt',
    ticker: 'CLH',
    name: 'Cementos Argos - Concesión',
    description: 'Concesiones viales y aeroportuarias (Odinsa)',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 8200,
    currentPriceOriginal: 8200,
    icon: '🛣️',
    color: '#00529B',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'elcondor',
    ticker: 'ELCONDOR',
    name: 'El Cóndor S.A.',
    description: 'Construcción de infraestructura vial',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 1450,
    currentPriceOriginal: 1450,
    icon: '🏗️',
    color: '#1E3A5F',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'conconcreto',
    ticker: 'CONCONCRETO',
    name: 'Constructora Conconcreto S.A.',
    description: 'Construcción de edificaciones e infraestructura',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 380,
    currentPriceOriginal: 380,
    icon: '🏢',
    color: '#E21A23',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Sector Servicios Públicos ---
  {
    id: 'epm',
    ticker: 'EPM',
    name: 'Empresas Públicas de Medellín',
    description: 'Servicios públicos: energía, agua, gas, telecomunicaciones',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 3100,
    currentPriceOriginal: 3100,
    icon: '💧',
    color: '#00A651',
    isAvailableInMGC: false,
    isPopular: false,
  },

  // --- Otras empresas relevantes ---
  {
    id: 'avianca',
    ticker: 'PFAVH',
    name: 'Avianca Holdings (Preferencial)',
    description: 'Aerolínea bandera de Colombia',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 3500,
    currentPriceOriginal: 3500,
    icon: '✈️',
    color: '#E31937',
    isAvailableInMGC: false,
    isPopular: true,
  },
  {
    id: 'terpel',
    ticker: 'TERPEL',
    name: 'Organización Terpel S.A.',
    description: 'Distribución de combustibles y lubricantes',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 9800,
    currentPriceOriginal: 9800,
    icon: '⛽',
    color: '#FFD100',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'colombina',
    ticker: 'COLOMBINA',
    name: 'Colombina S.A.',
    description: 'Confitería y alimentos: Bon Bon Bum, Nucita, Chocmelos',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 4200,
    currentPriceOriginal: 4200,
    icon: '🍬',
    color: '#E31937',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'biomax',
    ticker: 'BIOMAX',
    name: 'Biomax Biocombustibles',
    description: 'Distribución de combustibles y biocombustibles',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 1100,
    currentPriceOriginal: 1100,
    icon: '🌱',
    color: '#00A651',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'pei',
    ticker: 'PEI',
    name: 'Patrimonio Estratégico Industrial',
    description: 'Fondo inmobiliario industrial y logístico',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 185000,
    currentPriceOriginal: 185000,
    icon: '🏭',
    color: '#1E3A5F',
    isAvailableInMGC: false,
    isPopular: false,
  },
  {
    id: 'hcolsel_bvc',
    ticker: 'HCOLSEL',
    name: 'Hcolsel ETF',
    description: 'ETF que replica principales acciones colombianas',
    type: 'stock',
    category: 'colombia_stock',
    market: 'colombia',
    currency: 'COP',
    exchange: 'BVC',
    currentPriceCop: 8200,
    currentPriceOriginal: 8200,
    icon: '📈',
    color: '#003893',
    isAvailableInMGC: false,
    isPopular: false,
  },
];

// ============ MERCADO GLOBAL COLOMBIANO (MGC) ============
// Acciones internacionales que se pueden comprar directamente en la BVC

export const MGC_INSTRUMENTS: Instrument[] = [
  // --- Tecnología ---
  {
    id: 'mgc_aapl',
    ticker: 'AAPL',
    tickerAlphaVantage: 'AAPL',
    name: 'Apple Inc.',
    description: 'Empresa tecnológica: iPhone, Mac, servicios. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🍎',
    color: '#A2AAAD',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_msft',
    ticker: 'MSFT',
    tickerAlphaVantage: 'MSFT',
    name: 'Microsoft Corporation',
    description: 'Software, cloud computing, gaming. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1764000,
    currentPriceOriginal: 420,
    icon: '🪟',
    color: '#00A4EF',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_googl',
    ticker: 'GOOGL',
    tickerAlphaVantage: 'GOOGL',
    name: 'Alphabet Inc. (Google)',
    description: 'Búsqueda, publicidad, YouTube, cloud. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🔍',
    color: '#4285F4',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_amzn',
    ticker: 'AMZN',
    tickerAlphaVantage: 'AMZN',
    name: 'Amazon.com Inc.',
    description: 'E-commerce, AWS cloud, streaming. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 840000,
    currentPriceOriginal: 200,
    icon: '📦',
    color: '#FF9900',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_meta',
    ticker: 'META',
    tickerAlphaVantage: 'META',
    name: 'Meta Platforms Inc.',
    description: 'Facebook, Instagram, WhatsApp, VR. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2520000,
    currentPriceOriginal: 600,
    icon: '👤',
    color: '#0668E1',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_nvda',
    ticker: 'NVDA',
    tickerAlphaVantage: 'NVDA',
    name: 'NVIDIA Corporation',
    description: 'GPUs, inteligencia artificial, gaming. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 5040000,
    currentPriceOriginal: 1200,
    icon: '🎮',
    color: '#76B900',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_tsla',
    ticker: 'TSLA',
    tickerAlphaVantage: 'TSLA',
    name: 'Tesla Inc.',
    description: 'Vehículos eléctricos, energía solar. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1050000,
    currentPriceOriginal: 250,
    icon: '🚗',
    color: '#CC0000',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_nflx',
    ticker: 'NFLX',
    tickerAlphaVantage: 'NFLX',
    name: 'Netflix Inc.',
    description: 'Streaming de video y producción de contenido. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2940000,
    currentPriceOriginal: 700,
    icon: '🎬',
    color: '#E50914',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_adbe',
    ticker: 'ADBE',
    tickerAlphaVantage: 'ADBE',
    name: 'Adobe Inc.',
    description: 'Software creativo: Photoshop, Illustrator, Premiere. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2100000,
    currentPriceOriginal: 500,
    icon: '🎨',
    color: '#FF0000',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_crm',
    ticker: 'CRM',
    tickerAlphaVantage: 'CRM',
    name: 'Salesforce Inc.',
    description: 'CRM y software empresarial en la nube. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1260000,
    currentPriceOriginal: 300,
    icon: '☁️',
    color: '#00A1E0',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_orcl',
    ticker: 'ORCL',
    tickerAlphaVantage: 'ORCL',
    name: 'Oracle Corporation',
    description: 'Base de datos, cloud empresarial. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🗄️',
    color: '#F80000',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_intc',
    ticker: 'INTC',
    tickerAlphaVantage: 'INTC',
    name: 'Intel Corporation',
    description: 'Semiconductores y procesadores. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 126000,
    currentPriceOriginal: 30,
    icon: '💻',
    color: '#0071C5',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_amd',
    ticker: 'AMD',
    tickerAlphaVantage: 'AMD',
    name: 'Advanced Micro Devices',
    description: 'Procesadores y GPUs para gaming y servidores. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 588000,
    currentPriceOriginal: 140,
    icon: '🔲',
    color: '#ED1C24',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_csco',
    ticker: 'CSCO',
    tickerAlphaVantage: 'CSCO',
    name: 'Cisco Systems Inc.',
    description: 'Redes, comunicaciones y ciberseguridad. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 252000,
    currentPriceOriginal: 60,
    icon: '🌐',
    color: '#049FD9',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Sector Financiero ---
  {
    id: 'mgc_jpm',
    ticker: 'JPM',
    tickerAlphaVantage: 'JPM',
    name: 'JPMorgan Chase & Co.',
    description: 'Banco de inversión más grande de EE.UU. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 840000,
    currentPriceOriginal: 200,
    icon: '🏦',
    color: '#117ACA',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_bac',
    ticker: 'BAC',
    tickerAlphaVantage: 'BAC',
    name: 'Bank of America Corp.',
    description: 'Segundo banco más grande de EE.UU. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 168000,
    currentPriceOriginal: 40,
    icon: '🏦',
    color: '#012169',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_wfc',
    ticker: 'WFC',
    tickerAlphaVantage: 'WFC',
    name: 'Wells Fargo & Co.',
    description: 'Banca comercial y servicios financieros. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 294000,
    currentPriceOriginal: 70,
    icon: '🏦',
    color: '#D71E28',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_gs',
    ticker: 'GS',
    tickerAlphaVantage: 'GS',
    name: 'Goldman Sachs Group Inc.',
    description: 'Banca de inversión y gestión de activos. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2100000,
    currentPriceOriginal: 500,
    icon: '💼',
    color: '#7399C6',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_v',
    ticker: 'V',
    tickerAlphaVantage: 'V',
    name: 'Visa Inc.',
    description: 'Red de pagos global. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1302000,
    currentPriceOriginal: 310,
    icon: '💳',
    color: '#1A1F71',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_ma',
    ticker: 'MA',
    tickerAlphaVantage: 'MA',
    name: 'Mastercard Inc.',
    description: 'Red de pagos y tecnología financiera. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2016000,
    currentPriceOriginal: 480,
    icon: '💳',
    color: '#EB001B',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_pypl',
    ticker: 'PYPL',
    tickerAlphaVantage: 'PYPL',
    name: 'PayPal Holdings Inc.',
    description: 'Pagos digitales y fintech. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 336000,
    currentPriceOriginal: 80,
    icon: '💰',
    color: '#003087',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_brk_b',
    ticker: 'BRK.B',
    tickerAlphaVantage: 'BRK-B',
    name: 'Berkshire Hathaway Inc. Clase B',
    description: 'Holding de Warren Buffett. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1890000,
    currentPriceOriginal: 450,
    icon: '🏛️',
    color: '#2C3E50',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_nu',
    ticker: 'NU',
    tickerAlphaVantage: 'NU',
    name: 'Nu Holdings Ltd. (Nubank)',
    description: 'Banco digital líder en Latinoamérica. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 58800,
    currentPriceOriginal: 14,
    icon: '💜',
    color: '#820AD1',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_meli',
    ticker: 'MELI',
    tickerAlphaVantage: 'MELI',
    name: 'MercadoLibre Inc.',
    description: 'E-commerce y fintech líder en Latinoamérica. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 8400000,
    currentPriceOriginal: 2000,
    icon: '🛍️',
    color: '#FFE600',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_sq',
    ticker: 'SQ',
    tickerAlphaVantage: 'SQ',
    name: 'Block Inc. (Square)',
    description: 'Pagos digitales, Cash App, Bitcoin. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 336000,
    currentPriceOriginal: 80,
    icon: '⬛',
    color: '#000000',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_sofi',
    ticker: 'SOFI',
    tickerAlphaVantage: 'SOFI',
    name: 'SoFi Technologies Inc.',
    description: 'Fintech: préstamos, inversiones, banca digital. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 54600,
    currentPriceOriginal: 13,
    icon: '🏠',
    color: '#00D4AA',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_coin',
    ticker: 'COIN',
    tickerAlphaVantage: 'COIN',
    name: 'Coinbase Global Inc.',
    description: 'Exchange de criptomonedas más grande de EE.UU. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1050000,
    currentPriceOriginal: 250,
    icon: '🪙',
    color: '#0052FF',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_hood',
    ticker: 'HOOD',
    tickerAlphaVantage: 'HOOD',
    name: 'Robinhood Markets Inc.',
    description: 'Plataforma de trading sin comisiones. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 84000,
    currentPriceOriginal: 20,
    icon: '🪶',
    color: '#00C805',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Sector Consumo ---
  {
    id: 'mgc_ko',
    ticker: 'KO',
    tickerAlphaVantage: 'KO',
    name: 'The Coca-Cola Company',
    description: 'Bebidas: Coca-Cola, Fanta, Sprite. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 252000,
    currentPriceOriginal: 60,
    icon: '🥤',
    color: '#F40009',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_pep',
    ticker: 'PEP',
    tickerAlphaVantage: 'PEP',
    name: 'PepsiCo Inc.',
    description: 'Bebidas y snacks: Pepsi, Lay\'s, Gatorade. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 714000,
    currentPriceOriginal: 170,
    icon: '🥤',
    color: '#004B93',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_wmt',
    ticker: 'WMT',
    tickerAlphaVantage: 'WMT',
    name: 'Walmart Inc.',
    description: 'Cadena de retail más grande del mundo. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 714000,
    currentPriceOriginal: 170,
    icon: '🛒',
    color: '#0071CE',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_cost',
    ticker: 'COST',
    tickerAlphaVantage: 'COST',
    name: 'Costco Wholesale Corp.',
    description: 'Club de precios mayoristas. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 3780000,
    currentPriceOriginal: 900,
    icon: '🏪',
    color: '#E31837',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_mcd',
    ticker: 'MCD',
    tickerAlphaVantage: 'MCD',
    name: 'McDonald\'s Corporation',
    description: 'Cadena de restaurantes de comida rápida. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1260000,
    currentPriceOriginal: 300,
    icon: '🍔',
    color: '#FFC72C',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_sbux',
    ticker: 'SBUX',
    tickerAlphaVantage: 'SBUX',
    name: 'Starbucks Corporation',
    description: 'Cadena de cafeterías global. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 420000,
    currentPriceOriginal: 100,
    icon: '☕',
    color: '#00704A',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_nke',
    ticker: 'NKE',
    tickerAlphaVantage: 'NKE',
    name: 'Nike Inc.',
    description: 'Ropa y calzado deportivo. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 336000,
    currentPriceOriginal: 80,
    icon: '👟',
    color: '#111111',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_pg',
    ticker: 'PG',
    tickerAlphaVantage: 'PG',
    name: 'Procter & Gamble Co.',
    description: 'Productos de consumo: Gillette, Pampers, Tide. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 672000,
    currentPriceOriginal: 160,
    icon: '🧴',
    color: '#003DA5',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Sector Salud ---
  {
    id: 'mgc_jnj',
    ticker: 'JNJ',
    tickerAlphaVantage: 'JNJ',
    name: 'Johnson & Johnson',
    description: 'Farmacéutica y productos de consumo. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 630000,
    currentPriceOriginal: 150,
    icon: '💊',
    color: '#D51900',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_pfe',
    ticker: 'PFE',
    tickerAlphaVantage: 'PFE',
    name: 'Pfizer Inc.',
    description: 'Farmacéutica global. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 126000,
    currentPriceOriginal: 30,
    icon: '💉',
    color: '#0093D0',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_unh',
    ticker: 'UNH',
    tickerAlphaVantage: 'UNH',
    name: 'UnitedHealth Group Inc.',
    description: 'Seguros de salud y servicios médicos. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2100000,
    currentPriceOriginal: 500,
    icon: '🏥',
    color: '#002677',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_abbv',
    ticker: 'ABBV',
    tickerAlphaVantage: 'ABBV',
    name: 'AbbVie Inc.',
    description: 'Biofarmacéutica: Humira, Botox. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🧬',
    color: '#071D49',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_mrk',
    ticker: 'MRK',
    tickerAlphaVantage: 'MRK',
    name: 'Merck & Co. Inc.',
    description: 'Farmacéutica: Keytruda, vacunas. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 504000,
    currentPriceOriginal: 120,
    icon: '💊',
    color: '#00857C',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_lly',
    ticker: 'LLY',
    tickerAlphaVantage: 'LLY',
    name: 'Eli Lilly and Company',
    description: 'Farmacéutica: diabetes, oncología. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 3360000,
    currentPriceOriginal: 800,
    icon: '🧪',
    color: '#E01933',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Sector Energía ---
  {
    id: 'mgc_xom',
    ticker: 'XOM',
    tickerAlphaVantage: 'XOM',
    name: 'Exxon Mobil Corporation',
    description: 'Petrolera más grande de EE.UU. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 462000,
    currentPriceOriginal: 110,
    icon: '🛢️',
    color: '#ED1C24',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_cvx',
    ticker: 'CVX',
    tickerAlphaVantage: 'CVX',
    name: 'Chevron Corporation',
    description: 'Energía integrada: petróleo y gas. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 630000,
    currentPriceOriginal: 150,
    icon: '⛽',
    color: '#0066B2',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Sector Industrial ---
  {
    id: 'mgc_cat',
    ticker: 'CAT',
    tickerAlphaVantage: 'CAT',
    name: 'Caterpillar Inc.',
    description: 'Maquinaria pesada y equipos de construcción. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1470000,
    currentPriceOriginal: 350,
    icon: '🚜',
    color: '#FFCD11',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_ba',
    ticker: 'BA',
    tickerAlphaVantage: 'BA',
    name: 'The Boeing Company',
    description: 'Aeronáutica y defensa. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 798000,
    currentPriceOriginal: 190,
    icon: '✈️',
    color: '#0033A0',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_hon',
    ticker: 'HON',
    tickerAlphaVantage: 'HON',
    name: 'Honeywell International Inc.',
    description: 'Conglomerado industrial diversificado. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 882000,
    currentPriceOriginal: 210,
    icon: '🏭',
    color: '#E31837',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_ge',
    ticker: 'GE',
    tickerAlphaVantage: 'GE',
    name: 'General Electric Company',
    description: 'Aviación, energía, salud. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '⚡',
    color: '#3B73B9',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_ups',
    ticker: 'UPS',
    tickerAlphaVantage: 'UPS',
    name: 'United Parcel Service Inc.',
    description: 'Logística y paquetería global. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 588000,
    currentPriceOriginal: 140,
    icon: '📦',
    color: '#351C15',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- Comunicaciones y Entretenimiento ---
  {
    id: 'mgc_dis',
    ticker: 'DIS',
    tickerAlphaVantage: 'DIS',
    name: 'The Walt Disney Company',
    description: 'Entretenimiento: parques, películas, Disney+. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 462000,
    currentPriceOriginal: 110,
    icon: '🏰',
    color: '#113CCF',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_cmcsa',
    ticker: 'CMCSA',
    tickerAlphaVantage: 'CMCSA',
    name: 'Comcast Corporation',
    description: 'Telecomunicaciones y medios: NBCUniversal. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 168000,
    currentPriceOriginal: 40,
    icon: '📺',
    color: '#000000',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_t',
    ticker: 'T',
    tickerAlphaVantage: 'T',
    name: 'AT&T Inc.',
    description: 'Telecomunicaciones y servicios móviles. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 84000,
    currentPriceOriginal: 20,
    icon: '📱',
    color: '#00A8E0',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_vz',
    ticker: 'VZ',
    tickerAlphaVantage: 'VZ',
    name: 'Verizon Communications Inc.',
    description: 'Telecomunicaciones y 5G. Disponible en MGC.',
    type: 'stock',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 168000,
    currentPriceOriginal: 40,
    icon: '📶',
    color: '#CD040B',
    isAvailableInMGC: true,
    isPopular: false,
  },

  // --- ETFs disponibles en MGC ---
  {
    id: 'mgc_spy',
    ticker: 'SPY',
    tickerAlphaVantage: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    description: 'ETF más grande que replica el S&P 500. Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2520000,
    currentPriceOriginal: 600,
    icon: '📊',
    color: '#228B22',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_qqq',
    ticker: 'QQQ',
    tickerAlphaVantage: 'QQQ',
    name: 'Invesco QQQ Trust',
    description: 'ETF NASDAQ-100 (tecnología). Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2100000,
    currentPriceOriginal: 500,
    icon: '💻',
    color: '#0891B2',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_ivv',
    ticker: 'IVV',
    tickerAlphaVantage: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    description: 'ETF S&P 500 de iShares. Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 2268000,
    currentPriceOriginal: 540,
    icon: '📈',
    color: '#3C3B6E',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'mgc_eem',
    ticker: 'EEM',
    tickerAlphaVantage: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    description: 'ETF de mercados emergentes. Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 176400,
    currentPriceOriginal: 42,
    icon: '🌏',
    color: '#DC2626',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_gld',
    ticker: 'GLD',
    tickerAlphaVantage: 'GLD',
    name: 'SPDR Gold Shares',
    description: 'ETF respaldado por oro físico. Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 1008000,
    currentPriceOriginal: 240,
    icon: '🥇',
    color: '#DAA520',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'mgc_slv',
    ticker: 'SLV',
    tickerAlphaVantage: 'SLV',
    name: 'iShares Silver Trust',
    description: 'ETF respaldado por plata física. Disponible en MGC.',
    type: 'etf',
    category: 'mgc',
    market: 'usa',
    currency: 'USD',
    exchange: 'MGC-BVC',
    currentPriceCop: 117600,
    currentPriceOriginal: 28,
    icon: '🥈',
    color: '#C0C0C0',
    isAvailableInMGC: true,
    isPopular: false,
  },
];

// ============ ACCIONES INDIVIDUALES USA (Acceso Directo) ============

export const STOCK_INSTRUMENTS: Instrument[] = [
  {
    id: 'aapl',
    ticker: 'AAPL',
    name: 'Apple Inc.',
    description: 'Empresa tecnológica: iPhone, Mac, servicios',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🍎',
    color: '#A2AAAD',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'msft',
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    description: 'Software, cloud computing, gaming',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 1764000,
    currentPriceOriginal: 420,
    icon: '🪟',
    color: '#00A4EF',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'googl',
    ticker: 'GOOGL',
    name: 'Alphabet Inc. (Google)',
    description: 'Búsqueda, publicidad, YouTube, cloud',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 756000,
    currentPriceOriginal: 180,
    icon: '🔍',
    color: '#4285F4',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'amzn',
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    description: 'E-commerce, AWS cloud, streaming',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 840000,
    currentPriceOriginal: 200,
    icon: '📦',
    color: '#FF9900',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'nvda',
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    description: 'GPUs, inteligencia artificial, gaming',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 5040000,
    currentPriceOriginal: 1200,
    icon: '🎮',
    color: '#76B900',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'tsla',
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    description: 'Vehículos eléctricos, energía solar, baterías',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 1050000,
    currentPriceOriginal: 250,
    icon: '🚗',
    color: '#CC0000',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'meta',
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    description: 'Facebook, Instagram, WhatsApp, VR',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPriceCop: 2520000,
    currentPriceOriginal: 600,
    icon: '👤',
    color: '#0668E1',
    isAvailableInMGC: true,
    isPopular: true,
  },
  {
    id: 'jpm',
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co.',
    description: 'Banco de inversión y servicios financieros',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 840000,
    currentPriceOriginal: 200,
    icon: '🏦',
    color: '#117ACA',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'jnj',
    ticker: 'JNJ',
    name: 'Johnson & Johnson',
    description: 'Farmacéutica, dispositivos médicos, consumo',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 630000,
    currentPriceOriginal: 150,
    icon: '💊',
    color: '#D51900',
    isAvailableInMGC: true,
    isPopular: false,
  },
  {
    id: 'ko',
    ticker: 'KO',
    name: 'The Coca-Cola Company',
    description: 'Bebidas: Coca-Cola, Fanta, Sprite, etc.',
    type: 'stock',
    category: 'individual',
    market: 'usa',
    currency: 'USD',
    exchange: 'NYSE',
    currentPriceCop: 252000,
    currentPriceOriginal: 60,
    icon: '🥤',
    color: '#F40009',
    isAvailableInMGC: true,
    isPopular: false,
  },
];

// ============ TODAS LAS OPCIONES ============

export const ALL_INSTRUMENTS: Instrument[] = [
  ...ETF_INSTRUMENTS,
  ...COLOMBIA_STOCK_INSTRUMENTS,
  ...MGC_INSTRUMENTS,
  ...STOCK_INSTRUMENTS,
];

// ============ HELPERS ============

/**
 * Obtiene instrumentos por categoría
 */
export function getInstrumentsByCategory(category: InstrumentCategory): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.category === category);
}

/**
 * Obtiene instrumentos por tipo
 */
export function getInstrumentsByType(type: InstrumentType): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.type === type);
}

/**
 * Obtiene solo los instrumentos populares
 */
export function getPopularInstruments(): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.isPopular);
}

/**
 * Obtiene instrumentos disponibles en el MGC
 */
export function getMGCInstruments(): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.isAvailableInMGC);
}

/**
 * Obtiene acciones de la Bolsa de Valores de Colombia
 */
export function getBVCStocks(): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.category === 'colombia_stock');
}

/**
 * Obtiene todos los instrumentos colombianos (ETFs + acciones BVC)
 */
export function getColombianInstruments(): Instrument[] {
  return ALL_INSTRUMENTS.filter(i => i.market === 'colombia');
}

/**
 * Busca un instrumento por ID
 */
export function getInstrumentById(id: string): Instrument | undefined {
  return ALL_INSTRUMENTS.find(i => i.id === id);
}

/**
 * Busca un instrumento por ticker
 */
export function getInstrumentByTicker(ticker: string): Instrument | undefined {
  return ALL_INSTRUMENTS.find(i => i.ticker.toUpperCase() === ticker.toUpperCase());
}

/**
 * Categorías disponibles con labels
 */
export const INSTRUMENT_CATEGORY_LABELS: Record<InstrumentCategory, string> = {
  sp500: 'S&P 500',
  total_market: 'Mercado Total',
  international: 'Internacional',
  emerging: 'Mercados Emergentes',
  bonds: 'Bonos',
  dividend: 'Dividendos',
  tech: 'Tecnología',
  colombia: 'ETFs Colombia',
  colombia_stock: 'Acciones BVC',
  mgc: 'Mercado Global Colombiano',
  individual: 'Acciones USA (Directo)',
};

/**
 * Tipos de instrumento con labels
 */
export const INSTRUMENT_TYPE_LABELS: Record<InstrumentType, string> = {
  etf: 'ETF',
  stock: 'Acción',
  bond_etf: 'ETF de Bonos',
};
